# Generated by Django 3.2.5 on 2021-07-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
